### ISSUE TITLE
Notice Undefined index profil

### ISSUE THREAD

**Issue by Spone** [telabotanica/ep-plugin#24]
Je viens de mettre à jour le plugin sur master, et j'ai la notice suivante sur toutes les pages :

    Notice: Undefined index: profil in /srv/www/wordpress-default/wp-content/plugins/telabotanica/profil-etendu/profil-etendu.php on line 26

Une idée ?

**Comment by matcho** [comment]
@Spone il faut mettre à jour le fichier de config `config.json` à la racine du dossier du plugin, en y plaçant l'ID d'un machin qui n'existe pas forcément et qu'on trouve dans la base de données; je m'en occupe en test et préprod dans la journée.

C'est un mécanisme **très** bancal, il faudra qu'on trouve mieux.

En attendant, as-tu une suggestion de bonne pratique pour afficher un message d'erreur propre du genre "merci de mettre à jour votre configuration" ?

**Comment by Spone** [comment]
Merci, et comment je fais en local du coup ?

Il faudrait au moins qu'il n'y ait pas de Notice en front. Après à voir, peut-être qu'il faut ajouter un message pour les administrateurs dans l'admin comme le font certains plugins ? Il doit y avoir un filter ou une action pour ça...

**Comment by matcho** [comment]
Oui tout à fait c'est ça qu'il faut faire, je vais regarder pour l'ajouter rapidement.

**Comment by matcho** [comment]
Réparé à bc4ec4711572027139bf556bdda1397a7714fed6
